// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:al_quran_api/src/models/ayah/ayah.dart';
import 'package:al_quran_api/src/models/chapter/chapter.dart';
import 'package:al_quran_api/src/models/juz/juz.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(ChapterAdapter());
    registerAdapter(JuzAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(ChapterAdapter());
    registerAdapter(JuzAdapter());
  }
}
